#version 450

layout(local_size_x = 16, local_size_y = 16) in;

// 输入图像
layout(binding = 0, rgba8) readonly uniform image2D srcImage;

// 输出图像
layout(binding = 1, rgba8) writeonly uniform image2D dstImage;

void main()
{
    ivec2 uv = ivec2(gl_GlobalInvocationID.xy);

    vec4 c = imageLoad(srcImage, uv);

    // 透明度写死
    c.rgb *= 0.5;
    //c.rgb = vec3(1.0,0.0,0.0);

    imageStore(dstImage, uv, c);
}
